services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-gateway-api
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      PORT: 3002
    extra_hosts:
      - "host.docker.internal:host-gateway"
